### PR TITLE
Resolve conflict with new SDK Style , CICD Process

### LINKED ISSUE #66: Need confirm process to update
Hi @johnpierson, is your are resolving conflict between branch master and branch dev?

### PR DESCRIPTION
**Pull request by chuongmep**
resolve #66 
CI/ CD tracking : https://github.com/chuongmep/RhythmForDynamo/actions/runs/5941457678

### CODE REVIEW

**Comment by johnpierson** [comment]
I think your view extension code needs updated from the master @chuongmep

**Comment by johnpierson** [comment]
@chuongmep nevermind, I will add back the view extension stuff later.

**Comment by chuongmep** [comment]
> I think your view extension code needs updated from the master @chuongmep

Yes, the time between US and SG killed me, I saw you merge to master, still confuse about that.

**Comment by johnpierson** [comment]
No problem. But for reference, I think any future PR needs to be from
scratch unfortunately.

**Comment by chuongmep** [comment]
@johnpierson normally, when I work with my code, I push to dev branch, any developer want collaborate they need follow up with that branch, and then if everything work well, code will merge to master. It also work well with your process? I just want confirm to know which branch is latest to avoid unnecessary incidents like this in the future.

**Comment by johnpierson** [comment]
Let me make a new dev branch based off of master before you move further.

**Comment by chuongmep** [comment]
thank you for that @johnpierson , that will help all collaborators who come after me

**Pull request merged**
