### PR TITLE
Fix workflow 

### PR DESCRIPTION
**Pull request by chuongmep**
Please try merge this workflow, if it still wrong, please delete your dev branch and create clone new dev from my branch with branch name is `vcho`

### CODE REVIEW

**Comment by johnpierson** [comment]
Do you use Visual Studio @chuongmep ? I am having trouble understanding how to tag a commit properly for the build

**Comment by johnpierson** [comment]
So it is building, I just suck at adding tags.

Is there a way to change how we version it? Or do I need to learn how to create tags while committing

**Comment by chuongmep** [comment]
> Do you use Visual Studio @chuongmep ? I am having trouble understanding how to tag a commit properly for the build

Yes, I'm using both Visual Studio and Rider to maintain code.

**Comment by chuongmep** [comment]
> 

You mean is you want to create tag for release version ?

**Comment by johnpierson** [comment]
Yes

**Comment by chuongmep** [comment]
Oh, for create tag to release, it still needs more step I still haven't finished yet, I will help on this weekend, basically it automaton release installer also.
Any issue with Visual Studio ?

**Comment by chuongmep** [comment]
> So it is building, I just suck at adding tags.
> 
> Is there a way to change how we version it? Or do I need to learn how to create tags while committing

You just need to create tag in changelog version. I will help that.

**Pull request merged**
