### PR TITLE
Rhythm version fixing

### PR DESCRIPTION
**Pull request by johnpierson**
In progress branch for making Rhythm multi version Compatible.

### CODE REVIEW

**Comment by chuongmep** [comment]
Hi @johnpierson , I checked with your pull request, It is follow with old process, can we consider use new SDK style ? I will do support for process Automation CI/CD ?

**Comment by johnpierson** [comment]
New SDK sounds fine to me! I can go ahead and merge mine if you want to
revise it after ?

**Comment by chuongmep** [comment]
Okay, let create new branch dev, and I will create pull request to this branch first, after that, if you feel like process, we will merge to master branch.

**Comment by johnpierson** [comment]
Awesome. Let me merge these changes to master. Some background: rhythm now
loads Revit nodes on the fly with a view extension. But I did change to
shared projects with specific versions as well.

**Comment by chuongmep** [comment]
" But I did change to
shared projects with specific versions as well."
No need that @johnpierson , I will help for that with new SDK Style

**Comment by johnpierson** [comment]
Hmm, I’ll have to review the PR pretty thoroughly then. As that’s all new
to me.

**Comment by chuongmep** [comment]
It will be easier than that @johnpierson , I will create all documentation to follow after create another pull request to help you can run with all version of Revit

**Comment by chuongmep** [comment]
Can you create new branch dev, I just create new pull request change to this branch and review first, before this pull request merge to master, this is my target : 
- you help me create new branch dev
- I change pull request new SDK style to dev branch 
- I create custom version configuration for project
- I create CI/CD process automation for package 
- I create new pull request to dev branch
- You compare with current process before this pull request merge to master, if it ok, close this pull request and merge branch dev to master, if it not good, merge your pull request.
- Done

**Comment by johnpierson** [comment]
That works for me! And I will leave my view extension and extension work on
the other branch for now and cherry pick it later.

**Pull request merged**
