### PR TITLE
Upgrade SDK Style

### PR DESCRIPTION
**Pull request by chuongmep**
- The first pull request update new SDK style for easy maintain

### CODE REVIEW

**Comment by johnpierson** [comment]
Thanks so much @chuongmep ! Let me get this merged. For future pull requests can you hang on until I get the branch “Version Fixing” merged?

**Comment by chuongmep** [comment]
Hi @johnpierson , let merge your pull request, I will modify after that

**Comment by johnpierson** [comment]
Much appreciated!

**Comment by johnpierson** [comment]
Created a dev branch and changed it here for you!

**Comment by chuongmep** [comment]
Nice, let me do for next step.

**Comment by johnpierson** [comment]
One thing I am looking for here, is for the end goal to give me a folder for each Revit version (because I will still be using the package manager). Is that doable with this setup?

**Comment by chuongmep** [comment]
@johnpierson , yes, it will support automation generate to Dynamo version match with Revit version, you can upload to Dynamo package manager if you want.

**Comment by johnpierson** [comment]
Very awesome. Thank you. Looking forward to seeing the changes! Looking
through your OpenMEP repo now to get an idea, awesome stuff.

**Comment by chuongmep** [comment]
@johnpierson this one not include in nuget online ? 
image

**Comment by johnpierson** [comment]
Oh, it isn't. But I should include that as well. lets leave the program
file references for now?

**Comment by chuongmep** [comment]
May be do it temp first, I will consider publish nuget to support nuget online.

**Comment by chuongmep** [comment]
@johnpierson did you have old version ? I need more than one version of 2024 but now I just install 2024 in my computer, can help me assitance that ? 
- 2022
- 2021
- 2023
- 2024 (Not 2024.1)
image

**Comment by johnpierson** [comment]
I only have 2024.1

**Comment by chuongmep** [comment]
Wow, let me create new pull request support latest version first , include on configuration, and after that we will need some guy volunter add more dll of old version to support full from 20 to 24.1

**Comment by johnpierson** [comment]
If you want to hold on for now, I can get those added this next week. I
don't want you to do a bunch of extra work, when I am still moving things.

**Comment by chuongmep** [comment]
For sure, We can colaborate after I create next pull request .

**Pull request merged**
